[[redirects]]
  from = "/api/*"
  to = "http://backend-ecommerce.atwebpages.com/:splat"
  status = 200
  force = true
  headers = {X-Forwarded-Proto = "https"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
